### ISSUE TITLE
ARGO 隧道 token是写三个还是一个

### ISSUE THREAD

**Issue by zero456** [20241204/s-c-f-serv00#1]
大佬好！
有三个隧穿域名分别用于vless、vmess和trojan，那么对应是不是应该有三个ARGO 隧道 token？
目前说明里面只有一个ARGO_AUTH变量，是不是也应该有三个？如果有三个，应该怎么设置名称？
谢谢！

**Comment by zero456** [comment]
不好意思看错了，是一个隧道带三个域名。

**Comment by 20241204** [comment]
> 不好意思看错了，是一个隧道带三个域名。

抱歉刚注册新的github账号，这几天一直再弄项目迁移和docker镜像构建调试，就没看到你的问题，看到你的回复我想你应该看明白了，那就好，我想我应该是具体描述了怎么在 cloudflare 上配置一个 token 对应多个二级或三级域名的创建步骤，你甚至可以根据自己的需求魔改爆改我的脚本，比如弄十几个代理协议(不知道serv00 或者 ct8 能不能抗住)，不过 serv00 还是 ct8 有时候就是会自动封印，所以也说不好保活可能没用，哪里不明白可以继续问我，如果我看到了的话或者有时间的话会回你的，抱歉，回复你的时间很晚了，刚把docker构建调试好，希望这个账号不会被封吧，你可以直接把我的项目复制过去自己默默使用，免得我哪天又被github干掉，你就找不到我了/(ㄒoㄒ)/~~

**Comment by zero456** [comment]
大佬，还有个事请教一下。这个脚本运行后，在go build cloudflared这一步总是失败，我把go的依赖都下载都不行。最后还是在GitHub上找了一个预编译的版本才运行起来。麻烦大佬查看一下。谢谢！在 2024年12月13日，03:18，20241204 ***@***.***> 写道：﻿

不好意思看错了，是一个隧道带三个域名。

抱歉刚注册新的github账号，这几天一直再弄项目迁移和docker镜像构建调试，就没看到你的问题，看到你的回复我想你应该看明白了，那就好，我想我应该是具体描述了怎么在 cloudflare 上配置一个 token 对应多个二级或三级域名的创建步骤，你甚至可以根据自己的需求魔改爆改我的脚本，比如弄十几个代理协议(不知道serv00 或者 ct8 能不能抗住)，不过 serv00 还是 ct8 有时候就是会自动封印，所以也说不好保活可能没用，哪里不明白可以继续问我，如果我看到了的话或者有时间的话会回你的，抱歉，回复你的时间很晚了，刚把docker构建调试好，希望这个账号不会被封吧，你可以直接把我的项目复制过去自己默默使用，免得我哪天又被github干掉，你就找不到我了/(ㄒoㄒ)/~~

**Comment by 20241204** [comment]
> 大佬，还有个事请教一下。这个脚本运行后，在go build cloudflared这一步总是失败，我把go的依赖都下载都不行。最后还是在GitHub上找了一个预编译的版本才运行起来。麻烦大佬查看一下。谢谢！

你说得对，我试过了之后也出现了这个问题 
```
# github.com/cloudflare/cloudflared/diagnostic
diagnostic/diagnostic.go:168:30: undefined: network.NetworkCollectorImpl
```
我一开始以为是cloudflare官方go代码的问题，因为我的shell脚本只是搬运工和编译的作用，涉及不到go语言，我也还在学习中，不过学习中断了，我没办法处理go代码，可是，当我尝试执行cloudflare官方的脚本来下载go库的时候，我发现，可能问题不是cloudflare官方代码的问题，我有个猜想，那就是go的某些库被 serv00 屏蔽了，不允许下载，这样我就永远无法构建freebse版本的cloudflare了，我的猜想依据如下
![image](https://github.com/user-attachments/assets/7c674d52-7f1e-4a54-9568-2fcb9f63fa77)
因此，编译不成，就只能找cloudflare非官方编译版本，并另起炉灶写了一个函数用于获取下载freebsd版本
```
 https://github.com/robvanoostenrijk/cloudflared-freebsd
```
我顺便更新了sing-box配置，这样应该就能正常使用了 sing-box 1.11 版本配服务器和客户端更新，1.11 版本废弃了 geoip geosite rule dns 和 outbounds 的部分配置，不过还好改的地方不是很多
希望能帮到你，你再试试？
